business_name:
  default: MyIT CRM  Software Company
business_slogan:
  default: The Best CRM Software for your Repair Shop
business_phone:
  default: '02 9999 8888'
business_toll_free:
  default: '02 9999 8888'
business_fax:
  default: '02 9999 8888'
business_mobile:
  default: '02 9999 8888'
business_email:
  default: admin@exmaple.com
business_address:
  default: '49 Fake Road'
business_number:
  default: 
meta_tags:
  default: 'CRM, FREE, Opensource, Repair, Business, Computer, IT, Shop'

