business_name:
  default: MyIT CRM Stuffs
business_slogan:
  default: The Best Free and opensource Repairs Business CRM Software!
business_phone:
  default: '02 9999 8888'
business_toll_free:
  default: '02 9999 8888'
business_fax:
  default: '02 9999 8888'
business_mobile:
  default: '02 9999 8888'
business_email:
  default: me@example.com
business_address:
  default: '45 Fake Road'

