development:
  secret_key_base: k6nwC4ZrcYSi6FKfKPGkPLpnON9j88el0aTWyT20MXlO24RUWKmWkDTlZjFiHOZUvcLNLWUp1BWGLlHrgvAXuuHXhDh67woTfK9NU2C6gR5iK7oslkAsN4j3gPiuK9L2

test:
  secret_key_base: k6nwC4ZrcYSi6FKfKPGkPLpnON9j88el0aTWyT20MXlO24RUWKmWkDTlZjFiHOZUvcLNLWUp1BWGLlHrgvAXuuHXhDh67woTfK9NU2C6gR5iK7oslkAsN4j3gPiuK9L2

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>